version: "3"

services:
  postgres:
    restart: always
    image: postgres:alpine
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - "5432:5432"

  django:
    restart: always
    build: .
    container_name: django
    command:
      - /bin/sh
      - -c
      - python manage.py collectstatic --no-input &&
        python -m gunicorn --bind 0.0.0.0:8000 --timeout 240 backend.wsgi:application --log-level debug -w 4 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started

volumes:
  pgdata: { }

networks:
  default:
    name: langchain-server_default
    external: true
